#!/bin/bash

SCHEDSIM="schedsim/schedsim"
RESULTSF="results"
schedulers=("RR" "SJF" "FCFS" "PRIO")

function generate_chart() {
	cd gantt-gplot/
	./generate_gantt_chart ../$1
	cd ../
}

echo "Elige fichero de ejemplo"
read fejemplo

while [ ! -f $fejemplo ] ;do
	echo "Error"
	echo "Elige fichero de ejemplo"
	read fejemplo
done


echo "CPU number?"
read cpu_number
while [ $cpu_number -gt 8 ] ;do
	echo "ERROR: CPU number?"
	read cpu_number
done

mkdir -p $RESULTSF
cp $fejemplo $RESULTSF/emulated


for sched in ${schedulers[@]}
do
	for ((i=1; $i<=$cpu_number; i++))
	do
		mkdir -p "$RESULTSF/${i}cpus"
		$SCHEDSIM -n $cpu_number -s $sched -i "$fejemplo"
		for ((j=0; $j<$i; j++)) ;do
			mv CPU_$j.log "$RESULTSF/${i}cpus/${sched}-CPU-${j}.log"
			generate_chart "$RESULTSF/${i}cpus/${sched}-CPU-${j}.log"
		done
	done
done
